spring:
  application:
    name: todo_service
  profiles:
    active: dev
  config:
    import:
      - "optional:configserver:http://localhost:15001/"
#      - "optional:classpath:oAuth2_google-secret.yml"
