spring:
  application:
    name: auth_service
  profiles:
    active: dev
  config:
    import:
      - "optional:configserver:http://localhost:15001/"
      - "optional:classpath:oAuth2_google-secret.yml"

jwt:
  keystore:
    path: classpath:keys/myKey.jks
    password: rahat1722
    key-alias: rahat
  expiration: 86400000 # 24 hours
  refreshTokenExpiration: 604800000 # 7 days